### ISSUE TITLE
Question about gpt4_descriptors/sun397-gpt4.json

### ISSUE THREAD

**Issue by Git-L1** [elaine-sui/TPS#1]
Hello elaine-sui,
First of all, thank you for creating this amazing project!
I'm encountering an issue while using the project, and I would appreciate your help. Here are the details:
In gpt4_descriptors/sun397-gpt4.json , "wet_bar": [ ] , it seems that there is a missing corresponding value.
Thanks in advance for your time and assistance!
Best regards,
Git-L1

**Comment by elaine-sui** [comment]
Hi! So sorry for the late reply! I just updated the file in the repo!

**Comment by Git-L1** [comment]
ok, thanks!
